version: 2.1
orbs:
  docker: circleci/docker@2.1.2

jobs:
  build:
    description: Setup laravel application and run
    docker:
      # Specify the version you desire here
      - image: cimg/php:8.3.0
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Generate environmnet"
          command: php artisan env:decrypt --key=${ENV_SECRET_KEY}
      - run:
          name: "Build Environment"
          command: |
            ./vendor/bin/sail up

  # check-lint:
  #   description: Check convention of repo
  #   steps:
  #     - run:
  #         name: Run Check Convention
  #         command:
  #           ./vendor/bin/sail pint .

  test:
    description: Check Unit Test
    steps:
      - run:
          name: Run Unit Tests
          command: sail test

workflows:
  pipeline:
    jobs:
      - build
      # - check-lint:
      #     requires:
      #       - build
      - test:
          requires:
            - build




