version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.3-browsers
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: "Init Temp ENV"
          command: cp .env.example .env
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: composer install

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Set Up Docker"
          command: |
            docker-compose up --build
      - run:
          name: "Generate environmnet file"
          command: |
            ./vendor/bin/sail artisan env:decrypt --key=${ENV_SECRET_KEY} --force
            ./vendor/bin/sail down --volumes

      - run:
          name: "Run Environment"
          command: ./vendor/bin/sail up

  check-lint:
    docker:
      - image: cimg/php:8.2.0
    steps:
      - checkout
      - run:
          name: Run Check Convention
          command: ./vendor/bin/sail pint .

  test:
    docker:
      - image: cimg/php:.0
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: sail test

workflows:
  pipeline:
    jobs:
      - build
      - check-lint:
          requires:
            - build
      - test:
          requires:
            - build
