version: 2.1
orbs:
  docker: circleci/docker@2.4.0
  php: circleci/php@x.y

jobs:
  install_php:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - php/install-php:
          version: '8.2'
  install_composer_packages:
    executor: php/default
    steps:
      - checkout
      - php/install-composer
      - php/install-packages
  build:
    executor: docker/docker
      # Specify the version you desire here
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Generate environmnet"
          command: php artisan env:decrypt --key=${ENV_SECRET_KEY}
      - run:
          name: "Build Environment"
          command: |
            ./vendor/bin/sail up

  check-lint:
    executor: docker/docker
    steps:
      - checkout
      - run:
          name: Run Check Convention
          command: ./vendor/bin/sail pint .

  test:
    executor: docker/docker
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: sail test

workflows:
  pipeline:
    jobs:
      - install_php
      - install_composer_packages
      - build
      - check-lint:
          requires:
            - build
      - test:
          requires:
            - build




