version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.6
executors:
  backend-executor:
    docker:
      - image: cimg/php:8.3-browsers
      - image: cimg/node:21.2.0
      - image: cimg/redis:7.2
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

jobs:
  build-and-test:
    executor: backend-executor
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: test_db
      DB_USERNAME: user
      DB_PASSWORD: passw0rd
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    steps:
      - browser-tools/install-browser-tools
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: |
            composer install --dev --ignore-platform-reqs
            npm install
            npm run build

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
            - ./node_modules
      - run:
          name: "Set up Environment"
          command: |
            cp .env.example .env
            php artisan key:generate
            cat .env
      - run:
          name: Waiting for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Waiting for Redis primary to be ready
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: "Run Migration"
          command: php artisan migrate
      - run:
          name: "Run Tool Check Style"
          command: ./vendor/bin/pint
      - run:
          name: "Run Unit Test"
          command: |
            mkdir -p ~/phpunit
            php artisan test --log-junit ~/phpunit/junit.xml
      - run:
          name: "Generate Coverage File"
          command: |
            mkdir -p ~/reports
            sudo pecl channel-update pecl.php.net
            sudo pecl install xdebug && sudo docker-php-ext-enable xdebug
            ./vendor/bin/phpunit --coverage-html ~/reports
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/reports
workflows:
  pipeline:
    jobs:
      - build-and-test
