version: 2.1
orbs:
  docker: circleci/docker@2.4.0

jobs:
  build:
    executor: docker/docker
      # Specify the version you desire here
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: "Build & Up Docker ENV"
          command: docker-compose up -d --build
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Generate environmnet"
          command: ./vendor/bin/sail artisan env:decrypt --key=${ENV_SECRET_KEY}
      - run:
          name: "Build Environment"
          command: |
            ./vendor/bin/sail down --volumes
            ./vendor/bin/sail up

  check-lint:
    executor: docker/docker
    steps:
      - checkout
      - run:
          name: Run Check Convention
          command: ./vendor/bin/sail pint .

  test:
    executor: docker/docker
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: sail test

workflows:
  pipeline:
    jobs:
      - build:
      - check-lint:
          requires:
            - build
      - test:
          requires:
            - build
